application:
  name: @name@
  version: @version@

spring:
  application:
    name: ${application.name}

camel:
  springboot:
    main-run-controller: true

databases:
  sso:
    url: jdbc:mysql://localhost/sso?useTimezone=true&serverTimezone=America/Sao_Paulo
    user: frota
    password: frota
    port: 3306
    database: sso
  monitriip:
    host: localhost
    port: 27017
    database: test

rabbitmq:
  url: localhost
  exchange: processador.monitriip
  queue: eventos.monitriip
  exchange-dlq: processador.monitriip.DLQ
  deadLetterQueue: eventos.monitriip.DLQ
  username: guest
  password: guest
  fallback-delay: 60000

logging:
  file: /var/log/m2m-monitriip-worker-processamento.log



