application:
  name: @name@
  version: @version@

spring:
  application:
    name: ${application.name}

camel:
  springboot:
    main-run-controller: true

server:
  port: 8080

databases:
  sso:
    url: jdbc:mysql://mysql-hml/sso?useTimezone=true&serverTimezone=America/Sao_Paulo
    user: frota
    password: frota
    port: 3306
    database: sso
  frota:
    url: jdbc:mysql://mysql-hml/frota_znh?useTimezone=true&serverTimezone=America/Sao_Paulo
    user: frota
    password: frota
    port: 3306
    database: frota_znh
  monitriip:
    host: localhost
    port: 27017
    database: monitriip

logging:
  file: /var/log/m2m-monitriip-worker-processamento.log



