application:
  name: @name@
  version: @version@

spring:
  application:
    name: ${application.name}

camel:
  springboot:
    main-run-controller: true

databases:
  frota:
    host: localhost
    port: 27017
    database: test
  monitriip:
    host: localhost
    port: 27017
    database: test

rabbitmq:
  url: localhost
  exchange: processador.monitriip
  queue: eventos.monitriip
  exchange-dlq: monitriip.processador.erro
  deadLetterQueue: eventos.monitriip.DLQ